# Generated by Django 2.2.2 on 2019-06-14 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('age', models.PositiveIntegerField()),
                ('status', models.CharField(max_length=255)),
                ('bio', models.TextField()),
            ],
        ),
    ]
